# Generated by Django 5.0 on 2023-12-23 16:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('description', models.CharField(default='', max_length=254, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 12, 24, 19, 11, 56, 60284))], verbose_name='Due Date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=6)),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Task Setting',
                'verbose_name_plural': 'Task Settings',
                'ordering': ('-created_date',),
            },
        ),
    ]
